### ISSUE TITLE
Copying an online level puts the copied level above the pinned level(s)

### ISSUE THREAD

**Issue by derpydudee** [deaen/level-pins#1]
The title says all. If you copy an online level (e.g cataclysm) and after copying it, got back to your created levels, the copied level appears above the pinned ones

https://github.com/user-attachments/assets/a5a24678-d3fe-482c-8451-ebe6cbf1e2b4

**Comment by deaen** [comment]
fixed this yesterday actually , just waiting for the update to get approved on the index!
